apiVersion: v1



kind: Pod



metadata: 

  name: multi-container

  labels:

    env: dev

    tier: frontend  

    costcenter: devops



spec:

  containers:

    - name: mohitpinkapp



      image: mohitsoniv/ubuntu:webappPink



      ports:

        - containerPort: 80

    - name: mohitappnavy

      image: mohitsoniv/ubuntu:webappNavy

      command:

        - "watch" 

        - "wget"

        -  "-qO-"

        -  "localhost"

        

        




